Controllers/LeavesController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using HRMMVC.Models;
using Microsoft.AspNet.Identity;
using HRMMVC.Manager;

namespace HRMMVC.Controllers
{
    [Authorize]
    public class LeavesController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // "leave_empl_index", "leave_ofil_index", "leave_ofil_entry", "leave_empl_entry","",

        public async Task<ActionResult> Index()
        {
            var empLeaves = db.EmpLeaves.OrderByDescending(s => s.CreatedOn).Include(e => e.Employees);
            return PartialView(await empLeaves.ToListAsync());
        }


        public ActionResult LeaveType(int Id)
        {
            var al = db.LeaveType.ToList();
            ViewBag.LeaveTyps = al;
            if (Id > 0)
            {
               var d = al.Where(f => f.Id == Id).SingleOrDefault();
                return PartialView(d);
            }
            return PartialView(new LeaveType());
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult LeaveType(int Id, LeaveType model)
        {
            var JsonResult = new { Status = "", Message = "", url = "" };
            if (!ModelState.IsValid)
            {
                var error = ModelState.Values.SelectMany(f => f.Errors).Select(f => f.ErrorMessage).ToList();
                JsonResult = new { Status = "Error", Message = string.Join(", ", error), url = "" };
                return Json(JsonResult, JsonRequestBehavior.AllowGet);
            }
            var exist = db.LeaveType.Where(f => f.Title.ToUpper() == model.Title.ToUpper()).Any();
            if (Id > 0)
            {
                if (Id == model.Id)
                {
                    LeaveType obj = db.LeaveType.Where(s => s.Id == Id).SingleOrDefault();
                    if (exist == false)
                    {
                        obj.Title = model.Title;
                    }
                    obj.LeavePeriod = model.LeavePeriod;
                    obj.EmployeeCredit = model.EmployeeCredit;
                    
                    db.SaveChanges();
                    JsonResult = new { Status = "OK", Message = "Updated Successfully", url = "/Leaves/LeaveType?id=0" };
                    return Json(JsonResult, JsonRequestBehavior.AllowGet);
                }
            }
           
            if (exist)
            {
                JsonResult = new { Status = "Warning", Message = "Already Exist", url = "/Leaves/LeaveType" };
                return Json(JsonResult, JsonRequestBehavior.AllowGet);
            }
            db.LeaveType.Add(model);
            db.SaveChanges();
            JsonResult = new { Status = "OK", Message = "Add Successfully", url = "/Leaves/LeaveType" };
            return Json(JsonResult, JsonRequestBehavior.AllowGet);
        }
        // GET: Leaves/Create

        public ActionResult EmpLeaveEntry()
        {
            var employee = db.Employee.ToList().Select(s => new
            {
                Text = s.EmployeeCode + ", N: " + s.Full_Name + ", F:" + s.Father_Name,
                Value = s.Id
            });
            var leavetuype = db.LeaveType.ToList().Select(f => new
            {
                Id = f.Id,
                Text = f.Title
            }).ToList();
            ViewBag.EmployeeId = new SelectList(employee, "Value", "Text");
            ViewBag.LeaveTypeId = new SelectList(leavetuype, "Id", "Text");

            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EmpLeaveEntry(EmpLeave empLeave)
        {
            var jsonmess = new { Status = "", Message = "", url = "" };
            if (!ModelState.IsValid)
            {
                var error = ModelState.Values.SelectMany(f => f.Errors).Select(f => f.ErrorMessage).ToList();
                var messa = string.Join(", ", error);
                jsonmess = new { Status = "Error", Message = messa, url = "" };
                return Json(jsonmess, JsonRequestBehavior.AllowGet);
            }
            if (IsAlready(empLeave))
            {
                jsonmess = new { Status = "Faild", Message = "Leave Already Assign", url = "" };
                return Json(jsonmess, JsonRequestBehavior.AllowGet);
            }
            empLeave.Id = Guid.NewGuid();
            empLeave.UserId = User.Identity.GetUserId();
            db.EmpLeaves.Add(empLeave);
            await db.SaveChangesAsync();
            jsonmess = new { Status = "OK", Message = "Successfull saved", url = "/Leaves/Index" };
            return Json(jsonmess, JsonRequestBehavior.AllowGet);
        }

        // GET: Leaves/Edit/5
        [Authorize(Roles = "Company Admin, leave_entry")]
        public async Task<ActionResult> EmpLeaveEdit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmpLeave empLeave = await db.EmpLeaves.FindAsync(id);
            if (empLeave == null)
            {
                return HttpNotFound();
            }
            var employee = db.Employee.ToList().Select(s => new
            {
                Text = s.EmployeeCode + ", N: " + s.Full_Name + ", F:" + s.Father_Name,
                Value = s.Id
            });
            ViewBag.EmployeesId = new SelectList(employee, "Value", "Text", empLeave.EmployeeId);
            return View(empLeave);
        }

        // POST: Leaves/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EmpLeaveEdit([Bind(Include = "Id,LeaveType,LeaveFromDate,LeaveToDate,ApplicationRef,EmployeeId,UserId,CreatedOn")] EmpLeave empLeave)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empLeave).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employee, "Id", "EmailAddress", empLeave.EmployeeId);
            return View(empLeave);
        }

        // GET: Leaves/Delete/5

        public ActionResult AllHoliDays()
        {
            var rec = db.HoliDays.OrderBy(f => f.LeaveFrom).ToList();
            return PartialView(rec);
        }


        public ActionResult HoliDays()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult HoliDays(HoliDays holidas)
        {
            var jsonmess = new { Status = "", Message = "", url = "" };
            if (!ModelState.IsValid)
            {
                var error = ModelState.Values.SelectMany(f => f.Errors).Select(f => f.ErrorMessage).ToList();
                jsonmess = new { Status = "Error", Message = string.Join(", ", error), url = "" };
                return Json(jsonmess, JsonRequestBehavior.AllowGet);
            }
            var exist = db.HoliDays.Where(f =>
            (f.LeaveFrom <= holidas.LeaveFrom && f.LeaveTo >= holidas.LeaveTo) ||
            (f.LeaveFrom >= holidas.LeaveFrom && f.LeaveTo <= holidas.LeaveTo) ||
            (f.LeaveFrom >= holidas.LeaveFrom && f.LeaveFrom <= holidas.LeaveTo) ||
            (f.LeaveFrom <= holidas.LeaveFrom && f.LeaveTo >= holidas.LeaveFrom)
            ).Any();

            if (exist)
            {
                jsonmess = new { Status = "Warning", Message = "Already Exist", url = "" };
                return Json(jsonmess, JsonRequestBehavior.AllowGet);
            }
            holidas.UpdatedOn = DateTime.UtcNow;
            holidas.TotalDays = CountDays(holidas.LeaveFrom, holidas.LeaveTo);
            db.HoliDays.Add(holidas);
            db.SaveChanges();

            jsonmess = new { Status = "OK", Message = "Successfully Saved", url = "/Leaves/AllHoliDays" };
            return Json(jsonmess, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetLeavesRec(Guid EmployeeId, int Type) 
        {
           
            var l = db.LeaveType.Where(f => f.Id == Type).SingleOrDefault();
            return Json("----", JsonRequestBehavior.AllowGet);
        }

        [NonAction]
        public bool IsAlready(EmpLeave eml)
        {
            var exist = db.EmpLeaves.Where(s => s.EmployeeId == eml.EmployeeId && (
            (s.LeaveFromDate <= eml.LeaveFromDate && s.LeaveToDate >= eml.LeaveFromDate) || 
            (s.LeaveFromDate > eml.LeaveFromDate && s.LeaveFromDate < eml.LeaveToDate))).ToList();
            if (exist.Count() > 0)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        public int CountDays(DateTime fdate, DateTime tdate)
        {

            int day = 0;
            for (DateTime date = fdate; date <= tdate; date = date.AddDays(1))
            {
                if (date.DayOfWeek != Settings.WeekEnd && date.DayOfWeek != Settings.ComWeekEnd)
                {
                    day += 1;
                }
            }
            return day;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




    }
}

Views/Leaves/AllHoliDays.cshtml
@model IEnumerable<HRMMVC.Models.HoliDays>


<div class="card">
    <div class="card-header">
       Holiday in this year
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LeaveFrom)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LeaveTo)
                    </th>

                    <th>Days</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @item.LeaveFrom.ToString("dd-MMM-yyyy")
                    </td>
                    <td>
                        @item.LeaveTo.ToString("dd-MMM-yyyy")
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.TotalDays)
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer">
            <a href="@Url.Action("HoliDays", "Leaves")" class="btn btn-outline-primary loadPartial float-right">+Enter New</a>
    </div>
</div>

Views/Leaves/Delete.cshtml
@model HRMMVC.Models.EmpLeave

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EmpLeave</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employees.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employees.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveFromDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveFromDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveToDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveToDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationRef)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

    </dl>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "ajaxform" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Leaves/EmpLeaveEdit.cshtml
@model HRMMVC.Models.EmpLeave



@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "ajaxform" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="card-body d-flex" style="background-color:beige;">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.LeaveType, htmlAttributes: new { @class = "control-label" })

                @Html.EnumDropDownListFor(model => model.LeaveType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LeaveType, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ApplicationRef, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.ApplicationRef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationRef, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                @Html.DropDownListFor(model => model.EmployeeId, new SelectList(ViewBag.EmployeesId, "Value", "Text"), "Select Employee", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.LeaveFromDate, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.LeaveFromDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeaveFromDate, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LeaveToDate, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.LeaveToDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeaveToDate, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="clearfix">
            <input type="submit" id="submit" value="Save" class="btn btn-outline-primary float-right" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Leaves/EmpLeaveEntry.cshtml
@model HRMMVC.Models.EmpLeave
@{
    ViewBag.title = "Employee Leaves Entry";
}




<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            Leave Entry
        </div>
        <div class="card-body">

            @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "ajaxform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.DropDownList("EmployeeId", null, "--Employee--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @*@Html.LabelFor(model => model.LeaveType, htmlAttributes: new { @class = "control-label" })*@

                    @Html.DropDownList("LeaveTypeId", null, "--Leave Type--", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LeaveType, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.EditorFor(model => model.ApplicationRef, new { htmlAttributes = new { @class = "form-control", @placeholder = "Application Ref." } })
                    @Html.ValidationMessageFor(model => model.ApplicationRef, "", new { @class = "text-danger" })

                </div>


                <div class="d-md-flex justify-content-md-between">
                    <div class="form-group">
                        @Html.LabelFor(model => model.LeaveFromDate, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.LeaveFromDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LeaveFromDate, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LeaveToDate, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.LeaveToDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LeaveToDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="clearfix mt-2">
                    <input type="submit" id="submit" value="Save" class="btn btn-sm btn-outline-primary float-right" />
                </div>

            }
            <span id="leavetakenmessge"></span>
        </div>

        <div class="card-footer">
            <a href="/leaves/index" class="loadPartial btn btn-sm btn-secondary">Back To List</a>
        </div>
    </div>
</div>

<div id="javascript" data-function="LeavesEntry"></div>

Views/Leaves/HoliDays.cshtml
@model HRMMVC.Models.HoliDays

@{
    ViewBag.Title = "Holydays Entry";
}



<div class="col-md-6">
    <div class="card">
        <div class="card-header">
        Holy Days Entry
        </div>

        <div class="card-body">

            @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "ajaxform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-12 mb-3">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
                <div class="d-md-flex justify-content-between">
                    <div class="col-6">
                        @Html.LabelFor(model => model.LeaveFrom, htmlAttributes: new { @class = "control-label" })
                        <div class="c-input-group">
                            @Html.EditorFor(model => model.LeaveFrom, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LeaveFrom, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-6">
                        @Html.LabelFor(model => model.LeaveTo, htmlAttributes: new { @class = "control-label" })
                        <div class="c-input-group">
                            @Html.EditorFor(model => model.LeaveTo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LeaveTo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="clearfix">
                    <input type="submit" id="sbbtn" value="Save" class="btn btn-outline-primary float-right" />
                </div>
            }
        </div>
        <div class="card-footer">
            <a href="/Leaves/AllHoliDays" class="loadPartial btn btn-sm btn-secondary">Back to List</a>
        </div>
    </div>
</div>

Views/Leaves/Index.cshtml
@model IEnumerable<HRMMVC.Models.EmpLeave>
    @using HRMMVC.Models;



    <div class="card">
        <div class="card-header">Leave Records    </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Employee Name
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LeaveType)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LeaveFromDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LeaveToDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApplicationRef)
                            </th>
                            <th> Days Count</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @item.Employees.Full_Name
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LeaveType)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LeaveFromDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LeaveToDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApplicationRef)
                                </td>
                                <td>
                                    @{
                                        double Totalday = 0;
                                        for (DateTime index = item.LeaveFromDate; index <= item.LeaveToDate; index = index.AddDays(1))
                                        {
                                            if (index.DayOfWeek != DayOfWeek.Friday)
                                            {
                                                Totalday += 1;
                                            }
                                        }
                                        // var day = (item.LeaveTo.AddDays(1) - item.LeaveFrom).TotalDays;
                                    }
                                    @Totalday
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "EmpLeaveEdit", new { id = item.Id })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
            <div class="card-footer">
                <a href="@Url.Action("EmpLeaveEntry","Leaves")" class="btn btn-sm btn-primary float-right loadPartial">Leave Entry</a>
            </div>
        </div>

Views/Leaves/LeaveType.cshtml
@model HRMMVC.Models.LeaveType
@{
    var list = ViewBag.LeaveTyps as IEnumerable<HRMMVC.Models.LeaveType>;
    int i = 0;
}
<div class="card">
    <div class="card-header">
        Leave Type
    </div>
    <div class="card-body">

        <table class="table">
            <thead>
                <tr>
                    <th>Sl</th>
                    <th>Title</th>
                    <th>Emp. Ecedit</th>
                    <th>Period</th>
                    <th width="3%"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in list)
                {
                    i += 1;
                    <tr><td>@i</td><td>@item.Title</td><td>@item.EmployeeCredit</td><td>@item.LeavePeriod</td><td><a href="/Leaves/LeaveType?id=@item.Id" class="loadPartial"><i class="fa fa-pencil"></i></a></td></tr>
                }
            </tbody>
        </table>


        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "ajaxform" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="d-md-flex justify-content-md-between align-items-md-end">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-3">
                    @Html.LabelFor(model => model.EmployeeCredit, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.EmployeeCredit, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmployeeCredit, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-3">
                    @Html.LabelFor(model => model.LeavePeriod, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EnumDropDownListFor(model => model.LeavePeriod, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LeavePeriod, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2 text-right">
                    <input type="submit" value="Save" class="btn btn-sm btn-primary" />
                </div>
            </div>

        }
    </div>
</div>