Controllers/SalarysheetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using HRMMVC.Manager;
using HRMMVC.Models;
using Microsoft.AspNet.Identity;

namespace HRMMVC.Controllers
{
    [Authorize]
    public class SalarysheetsController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        // private ExtraFunctions ExtraFunctions = new ExtraFunctions();

        public ActionResult Index()
        {
            var salarysheet = db.Salarysheet.Include(s => s.Employee).Include(f => f.AllowancSalary).Include(f => f.Hourly_Duty).Include(f => f.AdvanceSalaryDeduction).OrderByDescending(f => f.SalaryType).Where(x => x.IsApproved == false);
            return PartialView(salarysheet.ToList());
        }

        public ActionResult PreviousSheet(DateTime? Month)  // need to updated with stm latest
        {
         var  month = Month ?? DateTime.UtcNow.Date;


            var salarysheet22 = db.Salarysheet.Where(m => m.IsApproved == true && m.FromDate.Month == month.Month && m.FromDate.Year == month.Year).Include(s => s.Employee).ToList();
            SalarySheetViewModel sl = new SalarySheetViewModel();
            List<Salarysheet_property> ps = new List<Salarysheet_property>();
            sl.Month = month.Date;
            foreach (var sh in salarysheet22)
            {
                Salarysheet_property p = new Salarysheet_property();
                p.Loan = sh.Loan;
                p.NetSalary = sh.NetSalary;
                p.BasicSalary = sh.BasicSalary;
                p.GrossSalary = sh.GrossSalary;
                p.Office_Holiday = sh.Office_Holiday;
                p.Paid_Leave = sh.Paid_Leave;
                p.Presents = sh.Presents;
                p.Pay_Full_Month = sh.Pay_Full_Month;
                p.SalaryType = sh.SalaryType;
                p.ToDate = sh.ToDate;
                p.TotalLeave = sh.TotalLeave;
                p.UnPaid_Leave = sh.UnPaid_Leave;
                p.TotalWorkDays = sh.TotalWorkDays;
                p.Absence = (int)sh.Absence;
                p.Advance = sh.Advance;
                p.Approved_By = sh.Approved_By;
                p.Designation = sh.Designation;
                p.FromDate = sh.FromDate;
                p.Full_Name = sh.Employee.Full_Name + " " + sh.Employee.Father_Name;
                p.Id = sh.Id;
                p.IshandOver = sh.IsHandover;

                var br = db.AllowanceSalary.Where(s => s.Id == sh.Id).ToList();
                var dr = db.AdvanceSalaryDeductions.Where(s => s.Id == sh.Id).SingleOrDefault();
                if (sh.SalaryType == SalaryTypes.Hourly)
                {
                    var hr = db.Hourly_Duty.Where(s => s.Id == sh.Id).SingleOrDefault();
                    p.OverTime_Hour = hr.Overtime_hour;
                    p.PayForHour = hr.PayforHour;
                    p.Rate_Per_Hour = hr.RatePerHour;
                }

                p.Bonus = ((decimal?)br.Sum(s => s.Benifited_Amount) ?? 0);
                p.Deduction = dr.Amount;
                ps.Add(p);
            }
            sl.Salarysheet_property = ps;
            return PartialView(sl);
        }


        public ActionResult Performance()
        {
            var department = db.Department.ToList().Select(f => new
            {
                Id = f.Id,
                Text = f.Name
            }).ToList();
            var shift = db.Shift.ToList().Select(f => new
            {
                Id = f.Id,
                Text = f.Name
            }).ToList();
            ViewBag.DepartmentId = new SelectList(department, "Id", "Text");
            ViewBag.ShiftId = new SelectList(shift, "Id", "Text");

            return PartialView();

        }
        [HttpPost]
        public ActionResult Performance(Guid[] EmployeeId, Performance[] Performance)
        {
            var jsmess = new { Status = "Faild", Message = "Something went wrong please try again", url = "" };

            if (EmployeeId.Length != Performance.Length)
            {
                return Json(jsmess, JsonRequestBehavior.AllowGet);
            }
            List<EmpPerformance> emf = new List<EmpPerformance>();
            for (int i = 0; i < EmployeeId.Length; i++)
            {
                var ep = new EmpPerformance()
                {
                    EmployeeId = EmployeeId[i],
                    Performance = Performance[i],
                    Month = DateTime.UtcNow.Date
                };
                emf.Add(ep);
            }
            foreach (var item in emf)
            {
                    item.Id = Guid.NewGuid();
                    db.EmpPerformance.Add(item);
            }
            db.SaveChanges();
            jsmess = new { Status = "OK", Message = "Successfully Saved", url = "/Salarysheets/Perpormance" };
            return Json(jsmess, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetEmployee(int? DepartmentId, int? ShiftId, int? DesignationId)
        {
            var all = db.Employee.Where(s => s.IsLeave == false).Include(f => f.Designation).ToList();
            if (DepartmentId > 0)
            {
                all = all.Where(s => s.Designation.DepartmentId == DepartmentId).ToList();
            }
            if (ShiftId > 0)
            {
                all = all.Where(s => s.ShiftId == ShiftId).ToList();
            }
            if (DesignationId > 0)
            {
                all = all.Where(s => s.DesignationId == DesignationId).ToList();
            }

            var jsondata = all.Select(f => new PerformanceViewModel
            {
                EmployeeId = f.Id,
                Name = f.Full_Name,
                Code = f.EmployeeCode,
            }).ToList();

            return PartialView("_SearchEmployee", jsondata);
        }

        public ActionResult Advance_History()
        {
            return PartialView();
        }
        [HttpGet]
        public ActionResult Get_Advance_Salary_Data() // Json Call
        {
            var emp = db.Employee.Include(f => f.Designation).ToList().Select(s => new
            {
                Name = s.Full_Name + " " + s.Father_Name,
                position = s.Designation.Title,
                Join_Date = s.JoiningDate.ToString("dd-MMM-yyyy hh:mm tt"),
                //  loan = (((decimal?)db.Employee_Loan.Where(m => m.EmployeeId == s.Id).ToList().Sum(a => a.Amount) ?? 0) - ((decimal?)db.Loan_Paid_history.Where(x => x.EmployeeId == s.Id).ToList().Sum(m => m.Amount)) ?? 0),
                Total_Advance = ((decimal?)db.Advance_Salary.Where(v => v.EmployeeId == s.Id).ToList()?.Sum(m => m.Amount) ?? 0),
                Paid = ((decimal?)db.AdvanceSalaryDeductions.Where(m => m.EmployeeId == s.Id).ToList()?.Sum(l => l.Amount) ?? 0),

            }).ToList();
            return Json(new { data = emp }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult NewPayslip()
        {
            var Empl = db.Employee.Where(s => s.IsLeave == false).ToList().Select(f => new
            {
                Id = f.Id,
                Text = f.Full_Name + ", " + f.EmployeeCode
            }).ToList();
            ViewBag.EmployeeId = new SelectList(Empl, "Id", "Text");
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewPayslip(Guid EmployeeId, DateTime Month)
        {
            var jsre = new { Status = "", Message = "", url = "" };

            Session["record"] = null;
            Session["benefits"] = null;
            Session["loss"] = null;
            int day = 1;
            int mo = Month.Month;
            int year = Month.Year;
            var fdate = new DateTime(year, mo, day);
            var tdate = fdate.AddMonths(1).AddDays(-1);

            Salarysheet salarysheet = new Salarysheet();
            var payroll = db.Payroll.Where(s => s.IsActive == true && s.EmployeeId == EmployeeId).Include(f => f.Payroll_Allowance).Include(f => f.Payroll_Deduction).SingleOrDefault();
            var empProfile = db.Employee.Include(f => f.Designation).Where(s => s.Id == EmployeeId && s.IsLeave == false).SingleOrDefault();
            var attendanceSumary = GetAttendanceSummary(EmployeeId, fdate, tdate);
            var checkp = (empProfile.JoiningDate.Month > fdate.Month && empProfile.JoiningDate.Year >= fdate.Year);
            var LastPayDate = db.Salarysheet.Where(a => a.EmployeeId == EmployeeId).Where(s => s.FromDate.Month == fdate.Month && s.FromDate.Year == fdate.Year).Any();
            if (LastPayDate)
            {
                jsre = new { Status = "Warning", Message = "Salary Already made for this employee on this month", url = "/Salarysheets/newpayslip" };
                return Json(jsre, JsonRequestBehavior.AllowGet);
            }
            if (checkp)
            {
                jsre = new { Status = "Warning", Message = "At your selected month This employee has not been started working on this company", url = "/Salarysheets/newpayslip" };
                return Json(jsre, JsonRequestBehavior.AllowGet);
            }
            if (!db.DailyAttendance.Where(f => f.EmployeeId == EmployeeId && f.Date.Month == fdate.Month && f.Date.Year == fdate.Year).Any())
            {
                jsre = new { Status = "Warning", Message = "Attendance record has not been inserted yet", url = "/Salarysheets/newpayslip" };
                return Json(jsre, JsonRequestBehavior.AllowGet);
            }
            if (payroll == null)
            {
                jsre = new { Status = "Warning", Message = "Payroll has not been setup yet", url = "/Salarysheets/newpayslip" };
                return Json(jsre, JsonRequestBehavior.AllowGet);
            }

            decimal As = GetAdvanceSalaryReport(EmployeeId);

Views/Salarysheets/Advance_History.cshtml
<div class="card">
    <div class="card-header">
        Advance Salary History
    </div>
    <div class="card-body">
        <table class="table" id="advanceandloanTable">
            <thead>
                <tr>
                    <th>Sl</th>
                    <th>Employee Name</th>
                    <th>Designation</th>
                    <th>Join Date</th>
                    <th>Total Advance</th>
                    <th>Deducted</th>
                    <th>Current Advance</th>
                </tr>
            </thead>

        </table>
    </div>
    <div class="card-footer">
        <a href="/Salarysheets/Advance_salary" class="loadPartial btn btn-sm btn-primary float-right">New Advance Salary</a>
    </div>
</div>



<div id="javascript" data-function="SalarySheetsAdvanceHistory"></div>

Views/Salarysheets/Advance_Salary.cshtml
@model HRMMVC.Models.Advance_Salary
@{
    ViewBag.title = "Advance Salary";

}


<div class="col-md-8">
    <div class="card">
        <div class="card-header">
            Advance Salary
        </div>
        <div class="card-body">


            @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "ajaxform" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="" ">
                    @Html.LabelFor(model => model.EmployeeId, "Employee", htmlAttributes: new { @class = "control-label" })

                    <div class="c-input-group">
                        <span class="icon fa fa-hand-o-down"></span>
                        @Html.DropDownList("EmployeeId", null, "Select Employee", htmlAttributes: new { @class = "form-control chosen_select" })
                        @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="" ">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                    <div class="c-input-group">
                        <span class="icon fa fa-calendar"></span>
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="" ">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label" })
                    <div class="c-input-group">
                        <span class="icon fa fa-money"></span>
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @placeholder = "0000.00" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="" ">
                    @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label" })
                    <div class="c-input-group">
                        <span class="icon fa fa-sticky-note"></span>
                        @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control", @placeholder = "Notes" } })
                        @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="clearfix">
                    <input type="submit" value="Submit" class="btn btn-outline-success float-right" />
                </div>

            }

        </div>
        <div class="card-footer">
            <a href="/Salarysheets/Advance_History" class="loadPartial btn btn-sm btn-outline-success"> History</a>
        </div>
    </div>
</div>

Views/Salarysheets/ConfirmPayslip.cshtml
@model HRMMVC.Models.Salarysheet
@using HRMMVC.Models;

<page size="A4" class="p-4">
    <div class="card">
        <div class="card-header">
            Confirm Pay slip
        </div>
        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "ajaxform" }))
        {


            @Html.AntiForgeryToken()

            @Html.HiddenFor(model => model.Absence)
            @Html.HiddenFor(model => model.Presents)
            @Html.HiddenFor(model => model.SalaryType)
            @Html.HiddenFor(model => model.ToDate)
            @Html.HiddenFor(model => model.FromDate)
            @Html.HiddenFor(model => model.GrossSalary)
            @Html.HiddenFor(model => model.Hourly_Duty)
            @Html.HiddenFor(model => model.NetSalary)
            @Html.HiddenFor(model => model.OverTime_Rate)
            @Html.HiddenFor(model => model.Paid_Leave)
            @Html.HiddenFor(model => model.PayForDays)
            @Html.HiddenFor(model => model.Overtime_day)
            @Html.HiddenFor(model => model.Office_Holiday)
            @Html.HiddenFor(model => model.TotalWorkDays)
            @Html.HiddenFor(model => model.TotalLeave)
            @Html.HiddenFor(model => model.Loan)
            @Html.HiddenFor(model => model.Advance)
            @Html.HiddenFor(model => model.BasicSalary)
            @Html.HiddenFor(model => model.AllowancSalary)
            @Html.HiddenFor(model => model.DeductionsSalary)
            @Html.HiddenFor(model => model.AdvanceSalaryDeduction)
            @Html.HiddenFor(model => model.Designation)
            @Html.HiddenFor(model => model.EmployeeId)
            @Html.HiddenFor(model => model.Employee)
            @Html.HiddenFor(model => model.UnPaid_Leave)
            @Html.HiddenFor(model => model.Overtime_day)




            <div class="card-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <td>
                                Employee
                            </td>

                            <td class="salar-for-name">
                                @Html.DisplayFor(model => model.Employee.Full_Name)  (@Html.DisplayFor(model => model.Employee.EmployeeCode))
                            </td>
                        </tr>

                        <tr>

                            <td>
                                @Html.DisplayNameFor(model => model.Designation)
                            </td>

                            <td>
                                @Html.DisplayFor(model => model.Designation)
                            </td>
                        </tr>
                        <tr>

                            <td>
                                @Html.DisplayNameFor(model => model.FromDate)
                            </td>

                            <td>
                                @Model.FromDate.ToString("dd-MMM-yyyy")
                            </td>
                        </tr>
                        <tr>

                            <td>
                                @Html.DisplayNameFor(model => model.ToDate)
                            </td>

                            <td>
                                @Model.ToDate.ToString("dd-MMM-yyyy")
                            </td>
                        </tr>
                        <tr>

                            <td>
                                @Html.DisplayNameFor(model => model.SalaryType)
                            </td>

                            <td>
                                @Html.DisplayFor(model => model.SalaryType)
                            </td>
                        </tr>


                        <tr>

                            <td>
                                @Html.DisplayNameFor(model => model.Paid_Leave)
                            </td>

                            <td>
                                @Html.DisplayFor(model => model.Paid_Leave)
                            </td>
                        </tr>
                        <tr>

                            <td>
                                @Html.DisplayNameFor(model => model.UnPaid_Leave)
                            </td>

                            <td>
                                @Html.DisplayFor(model => model.UnPaid_Leave)
                            </td>
                        </tr>


                        <tr>

                            <td>
                                @Html.DisplayNameFor(model => model.BasicSalary)
                            </td>

                            <td>
                                @Html.DisplayFor(model => model.BasicSalary)
                            </td>
                        </tr>

                        @if (Model.SalaryType == SalaryTypes.Hourly)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayNameFor(model => model.OverTime_Rate) PH
                                </td>

                                <td>
                                    @Html.DisplayFor(model => model.OverTime_Rate) tk.
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Time
                                </td>
                                <td>
                                    <table class="table">
                                        <thead><tr><th>Title</th><th>Amount</th></tr></thead>
                                        <tbody>
                                            <tr><td>Working Hour</td><td> @Html.DisplayFor(model => model.Hourly_Duty.Total_Working_Hour) hours</td></tr>
                                            <tr><td>Duty Hour</td><td> @Html.DisplayFor(model => model.Hourly_Duty.PayforHour) hours</td></tr>
                                            <tr><td>Over hour</td><td> @Html.DisplayFor(model => model.Hourly_Duty.Overtime_hour) hours</td></tr>
                                            <tr><td>RP/h</td><td> @Html.DisplayFor(model => model.Hourly_Duty.RatePerHour) Tk.</td></tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>

                        }
                        else
                        {
                            <tr><td>Overtime Rate</td><td> @Html.DisplayFor(model => model.OverTime_Rate)</td></tr>
                            <tr>
                                <td>
                                    Time
                                </td>
                                <td>
                                    <table class="table">
                                        <thead><tr><th>Title</th><th>Amount</th></tr></thead>
                                        <tbody>
                                            <tr><td>Working days</td><td> @Html.DisplayFor(model => model.TotalWorkDays)</td></tr>
                                            <tr><td>Absense</td><td>  @Html.DisplayNameFor(model => model.Absence)</td></tr>
                                            <tr><td>Presents</td><td>  @Html.DisplayNameFor(model => model.Presents)</td></tr>

                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.DisplayNameFor(model => model.OverTime_Rate)
                                </td>

                                <td>
                                    @Html.DisplayFor(model => model.OverTime_Rate) tk. Per Day
                                </td>
                            </tr>
                        }
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.GrossSalary)
                            </td>

                            <td>
                                @Html.DisplayFor(model => model.GrossSalary)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Advance)
                            </td>
                            <td class="amount-notic">
                                @Html.DisplayFor(model => model.Advance)
                            </td>
                        </tr>




                        <tr>
                            <td>Allowance</td>
                            <td>
                                <table class="table">
                                    <thead><tr><th>Field</th><th>Amount</th><th>Notes</th></tr></thead>
                                    <tbody>
                                        @foreach (var item in Model.AllowancSalary)
                                        {
                                            <tr><td>@item.Benifited_Field</td><td>@item.Benifited_Amount</td><td>@item.Notes</td></tr>
                                        }
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>Deduction</td>
                            <td>
                                <table class="table">
                                    <thead><tr><th>Field</th><th>Amount</th><th>Notes</th></tr></thead>
                                    <tbody>
                                        @foreach (var item in Model.DeductionsSalary)
                                        {
                                            <tr><td>@item.Deduction_Field</td><td>@item.Deducted_Amount</td><td>@item.Notes</td></tr>
                                        }
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr>

                            <td>
                                @Html.DisplayNameFor(model => model.NetSalary)
                            </td>

                            <td class="net-amount">
                                @Html.DisplayFor(model => model.NetSalary)
                            </td>
                        </tr>

                    </tbody>
                </table>
                <div class="clearfix">
                    <div class="mt-3 mb-3 float-right">
                        <div class="checkbox">
                            @Html.LabelFor(model => model.Pay_Full_Month, htmlAttributes: new { @class = "control-label" })  &nbsp;
                            @Html.EditorFor(model => model.Pay_Full_Month)
                            @Html.ValidationMessageFor(model => model.Pay_Full_Month, null, new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @if (Model.Advance > 0)
                {
                    <div class="form-group">
                        @Html.LabelFor(model => model.AdvanceSalaryDeduction.Amount, htmlAttributes: new { @class = "control-label" })
                        @Html.Editor("deductionAmount", new { htmlAttributes = new { @type = "number", @class = "form-control" } })
                    </div>
                    <div class="form-group mt-1">
                        @Html.TextArea("Notes", new { @class = "form-control", @placeholder = "Deduction Notes" })
                    </div>

                }
                <input type="submit" value="Confirm" class="btn btn-sm btn-outline-primary" />

            </div>


        }
</page>

Views/Salarysheets/Index.cshtml
@model IEnumerable<HRMMVC.Models.Salarysheet>
@using HRMMVC.Models;


<page size="A4" layout="landscape" class="">
    <div class="d-none-p ">
        <div class="clearfix">
            <div class="btn-group float-right mb-2">
                <button type="button" class="btn btn-default fa fa-plus">@Html.ActionLink("New", "NewPayslip", null, new {@class= "loadPartial" })</button>
                <button type="button" class="btn btn-info fa fa-print" onclick="window.print()"> Print</button>
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="" id="pending_salarysheet" border="1" cellpadding="2" cellspacing="2">
            <thead>
                <tr>
                    <th class="">Sl No.</th>
                    <th class="">Full Name</th>
                    <th class="">Designation</th>
                    <th class="">Salary</th>
                    <th class="">RPH</th>
                    <th class="">WD</th>
                    <th class="">PH</th>
                    <th class="">O/T H</th>
                    <th class="">O/T A</th>
                    <th class="">Full Month?</th>
                    <th class="">Loan</th>
                    <th class="">Bonus</th>
                    <th class="">Deduction </th>
                    <th class="">Gross Salary</th>
                    <th class="">Net Salary </th>
                    <th class="">Action</th>
                </tr>
            </thead>
            <tbody>
                @{int i = 0; }
                @foreach (var item in Model)
                {
                    i += 1;

                    <tr>
                        <td>@i</td>
                        <td>@item.Employee.Full_Name </td>
                        <td>@item.Designation</td>
                        <td>@item.BasicSalary</td>

                        @if (item.SalaryType == SalaryTypes.Hourly)
                        {
                            <td>@item.Hourly_Duty.RatePerHour</td>
                            <td>@item.TotalWorkDays</td>
                            <td>@item.Presents</td>
                            <td>@item.Hourly_Duty.Overtime_hour</td>
                            <td>@{ var ota = Convert.ToInt32(item.Hourly_Duty.RatePerHour * item.Hourly_Duty.Overtime_hour);} @ota</td>
                        }
                        else
                        {
                            <td colspan="5"></td>
                        }
                        <td>@item.Pay_Full_Month</td>
                        <td>@item.Loan</td>
                        <td>@{var benfits = ((int?)item.AllowancSalary.ToList().Sum(s => s.Benifited_Amount) ?? 0);} @benfits</td>
                        <td>@item.AdvanceSalaryDeduction.Amount</td>
                        <td>@item.GrossSalary</td>
                        <td>@item.NetSalary</td>
                        <td>
                            <div class="btn-group">
                                @{

                                        <a class="btn btn-sm btn-outline-success loadPartial require-confirm" href="/salarysheets/Approve?id=@item.Id"><i class="fa fa-check"></i></a>
                                        <a class="btn btn-sm btn-outline-info loadPartial" href="/salarysheets/PaySlip?id=@item.Id"><i class="fa fa-info"></i></a>
                                        <a href="/salarysheets/Delete?Id=@item.Id"  class="btn btn-sm btn-outline-danger loadPartial require-confirm"><i class="fa fa-times"></i></a>
                                    
                                }
                            </div>
                        </td>
                    </tr>
                }



            </tbody>
        </table>
    </div>


</page>

Views/Salarysheets/Performance.cshtml
@{
    ViewBag.Title = "Entry";
}
<div class="card">
    <div class="card-header">
        Monthly Performance Entry
    </div>
    <div class="card-body">
        <div class="d-md-flex justify-content-between">
            @Html.DropDownList("DepartmentId", null, "--Department--", new { @class = "form-control", @placeholder = "Department" })
            @Html.DropDownList("ShiftId", null, "--Shift--", new { @class = "form-control", @placeholder = "Shift" })
            @Html.DropDownList("DesignationId", new SelectList(""), "--Designation--", new { @class = "form-control", @placeholder = "Designation" })
            <input type="button" id="SearchButton" value="Search" class="btn btn-sm btn-outline-success" />
        </div>

    </div>

    <hr />

    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "ajaxform" }))
    {
        @Html.AntiForgeryToken()
        <div class="card-body">
            <div class="clearfix" id="loademployeetable">

            </div>

        </div>
        <div class="card-footer clearfix">
            <a href="@Url.Action("Employee","Employees")" class="btn btn-sm btn-primary loadPartial">Add New Employee</a>
            <a href="@Url.Action("PrintIds","Employees")" class="btn btn-sm btn-success loadPartial">Print ID Card</a>
            <a href="@Url.Action("Performance","Salarysheets")" class="btn btn-sm btn-warning loadPartial">Update Performance</a>
            <a href="@Url.Action("EmpLeaveEntry","Leaves")" class="btn btn-sm btn-danger loadPartial">Leave Entry</a>
            <a href="@Url.Action("Entry","Attendance")" class="btn btn-sm btn-info loadPartial">Attendance Entry</a>
            <input type="button" value="Submit" id="submit-button" class="btn btn-sm btn-outline-success disabled float-right" />
        </div>
    }
</div>

        <div id="javascript" data-function="salarysheetsperformance"></div>